/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Supplier;

import Product.product_table;
import Table.table_page;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Istiak
 */
public class supplier_table extends javax.swing.JFrame {

    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    /**
     * Creates new form supplier_table
     */
    public supplier_table() {
        initComponents();
        getContentPane().setBackground(Color.pink);
        Toolkit tt=Toolkit.getDefaultToolkit();
        int w=(int)tt.getScreenSize().getWidth();
        int h=(int)tt.getScreenSize().getHeight();
        this.setSize(w, h);
        String dd="SELECT * FROM `supplier`";
        Showtable(dd);
        a.setText(""+Autoid());
    }
    void Connection(){
        
        try {
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/supershop", "root", "");
st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(supplier_table.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID NO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 210, 32);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(250, 140, 320, 32);

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bKeyPressed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(250, 180, 320, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SUPPLIER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 210, 32);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(250, 220, 320, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 210, 32);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dKeyPressed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(250, 260, 320, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("COMPANY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 210, 32);
        getContentPane().add(e);
        e.setBounds(250, 300, 320, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CONTACT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 300, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUPPLIER NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 20, 330, 60);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 380, 100, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 380, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 380, 100, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("DELETE");
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 380, 100, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(360, 380, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO", "SUPPLIER NAME", "ADDRESS", "COMPANY", "CONTACT"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(610, 140, 660, 380);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Supplier/exit.JPG"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1230, 0, 140, 30);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1330, 0, 40, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Supplier/back.JPG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 106, 33);

        jButton7.setText("back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(80, 0, 20, 30);

        jButton8.setText("back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 0, 20, 30);

        jButton9.setText("forward");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(40, 10, 20, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        b.requestFocus();
        }
    }//GEN-LAST:event_aKeyPressed

    private void bKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        c.requestFocus();
        }
    }//GEN-LAST:event_bKeyPressed

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
       // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        d.requestFocus();
        }
    }//GEN-LAST:event_cKeyPressed

    private void dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyPressed
       // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        e.requestFocus();
        }
    }//GEN-LAST:event_dKeyPressed
    //Autoid
    int Autoid(){int x=0;
    String ss="SELECT  `ID` FROM `supplier`";
    Connection();
        try {
            rs=st.executeQuery(ss);
            while(rs.next()){
            x=rs.getInt(1);
            }
            x++;
        } catch (SQLException ex) {
            Logger.getLogger(supplier_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    return x;
    }
    
    //Showtable
    void Showtable(String sq){Connection();
     DefaultTableModel ddt=(DefaultTableModel)jTable1.getModel();
            ddt.setRowCount(0);
              try { 
            rs=st.executeQuery(sq);
            while(rs.next()){
            ddt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(supplier_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // INSERT DATA
        String id=a.getText();
        String name=b.getText();
        String address=c.getText();
        String company=d.getText();
        String contact=e.getText();
        if(id.isEmpty()){
          JOptionPane.showMessageDialog(this, "id is Empty ??", "Empty!!", 1);
          a.requestFocus();
        }
        else if(name.isEmpty()){
          JOptionPane.showMessageDialog(this, "Name is Empty ??", "Empty!!", 1);
          b.requestFocus();
        }
        else if(address.isEmpty()){
          JOptionPane.showMessageDialog(this, "Address is Empty ??", "Empty!!", 1);
          c.requestFocus();
        }
        else if(company.isEmpty()){
          JOptionPane.showMessageDialog(this, "Company is Empty ??", "Empty!!", 1);
          d.requestFocus();
        }
        else if(contact.isEmpty()){
          JOptionPane.showMessageDialog(this, "Contact is Empty ??", "Empty!!", 1);
          e.requestFocus();
        }
        else{
            try {
String sq="INSERT INTO `supplier` (`ID`,`Supplier Name`,`Address`,`Company`,`Contact`) VALUES ('"+id+"','"+name+"','"+address+"','"+company+"','"+contact+"')";
                Connection();
                int i=st.executeUpdate(sq);
                if(i>=1){
                JOptionPane.showMessageDialog(this, "Data Insert Success ", "Successfully", JOptionPane.PLAIN_MESSAGE);
                String dd="SELECT * FROM `supplier`";
                Showtable(dd);
                Clear();
                b.requestFocus();
                }
                else{
                JOptionPane.showMessageDialog(this, "Data Insert Success ", "Successfully", JOptionPane.PLAIN_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(supplier_table.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Mouse Clicked
        DefaultTableModel ddt=(DefaultTableModel)jTable1.getModel();
        a.setText(ddt.getValueAt(jTable1.getSelectedRow(), 0).toString());
        b.setText(ddt.getValueAt(jTable1.getSelectedRow(), 1).toString());
        c.setText(ddt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        d.setText(ddt.getValueAt(jTable1.getSelectedRow(), 3).toString());
        e.setText(ddt.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    void Clear(){
    b.setText("");
    c.setText("");
    d.setText("");
    e.setText("");
    b.requestFocus();
    String dd="SELECT * FROM `supplier`";
    Showtable(dd);
        a.setText(""+Autoid());
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Clear
        Clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //exit bar
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Back
        table_page tp=new table_page();
        tp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //back
        table_page tp=new table_page();
        tp.setVisible(true);
        this.setVisible(false);
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Forward
        /*table_page tp=new table_page();
        tp.setVisible(false);
        this.setVisible(true);*/
    }//GEN-LAST:event_jButton9ActionPerformed

    void Update(){
        String id=a.getText();
        String name=b.getText();
        String address=c.getText();
        String company=d.getText();
        String contact=e.getText();
        if(name.isEmpty()){
          JOptionPane.showMessageDialog(this, "Name is Empty ??", "Empty!!", 1);
          b.requestFocus();
        }
        else if(address.isEmpty()){
          JOptionPane.showMessageDialog(this, "Address is Empty ??", "Empty!!", 1);
          c.requestFocus();
        }
        else if(company.isEmpty()){
          JOptionPane.showMessageDialog(this, "Company is Empty ??", "Empty!!", 1);
          d.requestFocus();
        }
        else if(contact.isEmpty()){
          JOptionPane.showMessageDialog(this, "Contact is Empty ??", "Empty!!", 1);
          e.requestFocus();
        }
        else{
            try {
String sq="UPDATE `supplier` SET `Supplier Name`='"+name+"',`Address`='"+address+"',`Company`='"+company+"',`Contact`='"+contact+"' WHERE `ID`='"+id+"'";
                Connection();
                int x=st.executeUpdate(sq);
                if(x>=1){
                JOptionPane.showMessageDialog(this, "Data Update Success ", "Successfully", JOptionPane.PLAIN_MESSAGE);
                String dd="SELECT * FROM `supplier`";
                Showtable(dd);
                Clear();
                b.requestFocus();
                }
                else{
                JOptionPane.showMessageDialog(this, "Data Update Failed ", "Un Successfully", JOptionPane.PLAIN_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(supplier_table.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
    
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Update
        Update();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
