/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_main;

import Product.product_table;
import java.awt.JobAttributes;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Istiak
 */
public class CreateTable extends javax.swing.JInternalFrame {
  

    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    /**
     * Creates new form CreateTable
     */
    public CreateTable() {
        initComponents();
    }
    void Con(){
        try {
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/supershop", "root", "");
st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        e = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Create User Account");
        getContentPane().setLayout(null);

        jLabel1.setText("Full Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 70, 350, 30);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(60, 100, 360, 30);

        jLabel2.setText("Permanent Address:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 250, 350, 30);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dKeyPressed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(60, 280, 360, 30);

        jLabel3.setText("BirthDay Date:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 370, 350, 30);

        jLabel4.setText("Father Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 130, 350, 30);

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bKeyPressed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(60, 160, 360, 30);

        jLabel5.setText("Present Address:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 350, 30);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(60, 220, 360, 30);

        jLabel6.setText("User Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 490, 350, 30);
        getContentPane().add(f);
        f.setBounds(70, 520, 360, 30);

        jLabel7.setText("Create Password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 550, 350, 30);
        getContentPane().add(g);
        g.setBounds(70, 580, 360, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin_main/c1.png"))); // NOI18N
        jLabel8.setText("Create Account");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 0, 190, 90);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 450, 110, 40);

        buttonGroup1.add(r1);
        r1.setText("Male");
        getContentPane().add(r1);
        r1.setBounds(170, 460, 70, 23);

        buttonGroup1.add(r2);
        r2.setText("Female");
        getContentPane().add(r2);
        r2.setBounds(260, 460, 70, 23);

        buttonGroup1.add(r3);
        r3.setText("Other");
        getContentPane().add(r3);
        r3.setBounds(340, 460, 60, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAY", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(60, 410, 70, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octob", "November", "December" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 410, 80, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 410, 90, 20);
        getContentPane().add(e);
        e.setBounds(60, 340, 360, 30);

        jLabel10.setText("Mobile No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 310, 350, 30);

        jLabel11.setText("Confirm Password");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 610, 350, 30);
        getContentPane().add(h);
        h.setBounds(70, 640, 360, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("INSERT ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 680, 100, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(360, 410, 130, 20);

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 690, 55, 20);

        setBounds(0, 0, 511, 754);
    }// </editor-fold>//GEN-END:initComponents

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        b.requestFocus();
        }
    }//GEN-LAST:event_aKeyPressed

    private void bKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        c.requestFocus();
        }
    }//GEN-LAST:event_bKeyPressed

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
       // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        d.requestFocus();
        }
    }//GEN-LAST:event_cKeyPressed

    private void dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyPressed
        // // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        e.requestFocus();
        }
    }//GEN-LAST:event_dKeyPressed



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Insert data

        String fullname=a.getText();
        String fathername=b.getText();
        String present=c.getText();
        String permanent=d.getText();
        String mobile=e.getText();

        String gender;
        if(r1.isSelected()){
            gender="Male";
        }
        else if(r2.isSelected()){
            gender="Female";
        }
        else if(r3.isSelected()){
            gender="Other";
        }
        else{
            gender="";
            JOptionPane.showMessageDialog(this, "Gender is empty");
        }

        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-mm-dd");
        String date=sdf.format(jDateChooser1.getDate());

        String username=f.getText();
        String createpass=g.getText();
        String confirmpass=h.getText();

        if(fullname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Full Name Empty !!");
            a.setText("");
        }
        else if(fathername.isEmpty()){
            JOptionPane.showMessageDialog(this, "Father Name Empty !!");
            b.requestFocus();
        }
        else if(present.isEmpty()){
            JOptionPane.showMessageDialog(this, "Present Address Empty !!");
            c.requestFocus();
        }
        else if(permanent.isEmpty()){
            JOptionPane.showMessageDialog(this, "Permanent Address Empty !!");
            d.requestFocus();
        }
        else if(mobile.isEmpty()){
            JOptionPane.showMessageDialog(this, "Mobile No. Empty !!");
            e.requestFocus();
        }
        /* else if(date.isEmpty()){
            JOptionPane.showMessageDialog(this, "BirthDay Date  Empty !!");

        }*/
        else if(gender.isEmpty()){
            JOptionPane.showMessageDialog(this, "gerder  Empty !!");
            r1.requestFocus();
        }
        else if(username.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Name Empty !!");
            f.setText("");
        }
        else if(createpass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Create Password Empty !!");
            g.setText("");
        }
        else if(confirmpass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Comfirm Password Empty !!");
            h.setText("");
        }
        else{
            try {
                Con();
                String sqq="INSERT INTO `create_account` (`Full Name`,`Father Name`,`Present Address`,`Permanent Address`,`Mobile No`,`BirthDay`,`Gender`,`User Name`,`Create Password`,`Confirm Password`) VALUES('"+fullname+"','"+fathername+"','"+present+"','"+permanent+"','"+mobile+"','"+date+"','"+gender+"','"+username+"','"+createpass+"','"+confirmpass+"')";

                int x=st.executeUpdate(sqq);
                if(x>0){
                    JOptionPane.showMessageDialog(this,"Data Insert Success ");
                    NextPassword np=new NextPassword();
                    np.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Data Insert Failed ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(CreateTable.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // next
        NextPassword np=new NextPassword();
        np.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    // End of variables declaration//GEN-END:variables
}
