/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_main;

/**
 *
 * @author Istiak
 */
public class NextPassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form NextPassword
     */
    public NextPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Create User Account");
        getContentPane().setLayout(null);

        jLabel1.setText("Confirm Password :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 180, 280, 30);

        jLabel2.setText("Create Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 120, 280, 30);

        jLabel3.setText("User Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 60, 280, 30);
        getContentPane().add(c);
        c.setBounds(80, 210, 290, 30);
        getContentPane().add(a);
        a.setBounds(80, 90, 290, 30);
        getContentPane().add(b);
        b.setBounds(80, 150, 290, 30);

        jButton1.setText("Previus");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 370, 90, 30);

        jButton2.setText("Create");
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 270, 90, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 270, 90, 30);

        setBounds(0, 0, 461, 453);
    }// </editor-fold>//GEN-END:initComponents

    void Clear(){
    a.setText("");
    b.setText("");
    c.setText("");
    a.requestFocus();
    
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Clear
        Clear();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
