/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Table.table_page;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Istiak
 */
public class customer_table extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;

    /**
     * Creates new form customer_table
     */
    public customer_table() {
        initComponents();
        getContentPane().setBackground(Color.pink);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int w=(int)tk.getScreenSize().getWidth();
        int h=(int)tk.getScreenSize().getHeight();
        this.setSize(w, h);
        String ss="SELECT *FROM `customer`";
        Showtable(ss);
        a.setText(""+Autoid());
        d.setText("@gmail.com");
        e.setText("+880 ");
        
    }
    void Con(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/supershop", "root", "");
            st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID NO.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 210, 29);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(270, 120, 290, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CUSTOMER TABLE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 20, 440, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CUSTOMER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 210, 29);

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bKeyPressed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(270, 160, 290, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ADDRESS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 210, 29);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(270, 200, 290, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("G-MAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 210, 29);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dKeyPressed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(270, 240, 290, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CONTACT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 280, 210, 29);
        getContentPane().add(e);
        e.setBounds(270, 280, 290, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 350, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 350, 90, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 350, 90, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 350, 90, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(360, 350, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO.", "CUSTOMER NAME", "ADDRESS", "G-MAIL", "CONTACT"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 120, 730, 380);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/back.JPG"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 110, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/exit.JPG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1240, 0, 130, 30);

        jButton7.setText("back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(80, 0, 30, 30);

        jButton6.setText("back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 0, 30, 30);

        jButton8.setText("exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1340, 0, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Delete
        String id=a.getText();
        String name=b.getText();
        String address=c.getText();
        String gmail=d.getText();
        String contact=e.getText();
        Con();
            try {
String sd="DELETE FROM`customer` WHERE `ID`='"+id+"' AND `Contact`='"+contact+"'";
           int d=st.executeUpdate(sd);
           if(d>=1){
           JOptionPane.showMessageDialog(this, "Delete Successful", "Successfully!!",JOptionPane.PLAIN_MESSAGE);
           clear();
           String ss="SELECT *FROM `customer`";
           Showtable(ss);
           }
           else{
           JOptionPane.showMessageDialog(this, "Delete Failed", "Failed!!",JOptionPane.PLAIN_MESSAGE);
           }
            } catch (SQLException ex) {
                Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        //ENTER
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        b.requestFocus();
        }
    }//GEN-LAST:event_aKeyPressed

    private void bKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyPressed
       //ENTER
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        c.requestFocus();
        }
    }//GEN-LAST:event_bKeyPressed

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
       //ENTER
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        d.requestFocus();
        }
    }//GEN-LAST:event_cKeyPressed
//Showtable
    
    void Showtable(String ss){
        DefaultTableModel ddt=(DefaultTableModel)jTable1.getModel();
        ddt.setRowCount(0);
        Con();
        try {
            rs=st.executeQuery(ss);
            while(rs.next()){
            ddt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



//Auto id 
    int Autoid(){int at=0;
        try {
        String au="SELECT `ID` FROM `customer`";
        Con();
        rs=st.executeQuery(au);
        while(rs.next()){
        at=rs.getInt(1);
        }
        at++;
        
        } catch (SQLException ex) {
            Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    return at;
    }
    
    private void dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyPressed
        //ENTER
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        e.requestFocus();
        }
    }//GEN-LAST:event_dKeyPressed

    void clear(){
    b.setText("");
    c.setText("");
    d.setText("");
    e.setText("");
    b.requestFocus();
    String ss="SELECT *FROM `customer`";
    Showtable(ss);
    d.setText(" @gmail.com");
        e.setText("+880 ");
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    //Clear
    clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Exit
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // back
        table_page tp=new table_page();
        this.setVisible(false);
        tp.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Insert data
        String id=a.getText();
        String name=b.getText();
        String address=c.getText();
        String gmail=d.getText();
        String contact=e.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID Is Empty", "Empty!!", 1);
            a.requestFocus();
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name Is Empty", "Empty!!", 1);
            b.requestFocus();
        }
        else if(address.isEmpty()){
            JOptionPane.showMessageDialog(this, "Address Is Empty", "Empty!!", 1);
            c.requestFocus();
        }
        else if(gmail.isEmpty()){
            JOptionPane.showMessageDialog(this, "G-mail Is Empty", "Empty!!", 1);
            d.requestFocus();
        }
        else if(contact.isEmpty()){
            JOptionPane.showMessageDialog(this, "Contact Is Empty", "Empty!!", 1);
            e.requestFocus();
        }
        else{
            Con();
            try {
String sq="INSERT INTO `customer` (`ID`,`Customer Name`,`Address`,`G-mail`,`Contact`) VALUES ('"+id+"','"+name+"','"+address+"','"+gmail+"','"+contact+"')";
           int i=st.executeUpdate(sq);
           if(i>=1){
           JOptionPane.showMessageDialog(this, "Insert Successful", "Successfully!!",JOptionPane.PLAIN_MESSAGE);
           clear();
           String ss="SELECT *FROM `customer`";
           Showtable(ss);
           a.setText(""+Autoid());
           }
           else{
           JOptionPane.showMessageDialog(this, "Insert Failed", "Failed!!",JOptionPane.PLAIN_MESSAGE);
           }
            } catch (SQLException ex) {
                Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Mouse Cliced
        DefaultTableModel ddt=(DefaultTableModel)jTable1.getModel();
        a.setText(ddt.getValueAt(jTable1.getSelectedRow(), 0).toString());
        b.setText(ddt.getValueAt(jTable1.getSelectedRow(), 1).toString());
        c.setText(ddt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        d.setText(ddt.getValueAt(jTable1.getSelectedRow(), 3).toString());
        e.setText(ddt.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Update
        String id=a.getText();
        String name=b.getText();
        String address=c.getText();
        String gmail=d.getText();
        String contact=e.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID Is Empty", "Empty!!", 1);
            a.requestFocus();
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name Is Empty", "Empty!!", 1);
            b.requestFocus();
        }
        else if(address.isEmpty()){
            JOptionPane.showMessageDialog(this, "Address Is Empty", "Empty!!", 1);
            c.requestFocus();
        }
        else if(gmail.isEmpty()){
            JOptionPane.showMessageDialog(this, "G-mail Is Empty", "Empty!!", 1);
            d.requestFocus();
        }
        else if(contact.isEmpty()){
            JOptionPane.showMessageDialog(this, "Contact Is Empty", "Empty!!", 1);
            e.requestFocus();
        }
        else{
           
            try {

String up="UPDATE `customer` SET `Customer Name`='"+name+"',`Address`='"+address+"',`G-mail`='"+gmail+"',`Contact`='"+contact+"' WHERE `ID`='"+id+"'";
       Con();     
int u=st.executeUpdate(up);
           if(u>=1){
           JOptionPane.showMessageDialog(this, "Update Successful", "Successfully!!",JOptionPane.PLAIN_MESSAGE);
           clear();
           }
           else{
           JOptionPane.showMessageDialog(this, "Update Failed", "Failed!!",JOptionPane.PLAIN_MESSAGE);
           }
            } catch (SQLException ex) {
                Logger.getLogger(customer_table.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // back
        table_page tp=new table_page();
        this.setVisible(false);
        tp.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // exit
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
