
package Product;

import Table.table_page;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Istiak
 */
public class product_table extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;

    /**
     * Creates new form product_table
     */
    public product_table() {
        initComponents();
        getContentPane().setBackground(Color.pink);
        Toolkit tt= Toolkit.getDefaultToolkit();
        int w=(int)tt.getScreenSize().getWidth();
        int h=(int)tt.getScreenSize().getHeight();
        this.setSize(w, h);
        String dd="SELECT * FROM `product`";
        Showtable(dd);
        a.setText(""+Autoid());
        jTable1.selectAll();
        
    }

    void Con(){
        try {
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/supershop", "root", "");
st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT TABLE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 0, 340, 70);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 260, 32);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(290, 110, 296, 32);

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bKeyPressed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(290, 150, 296, 32);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PRODUCT NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 260, 32);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(290, 190, 296, 32);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PRODUCT PRICE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 260, 32);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("QUANTITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 260, 32);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dKeyPressed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(290, 230, 120, 32);

        e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eKeyPressed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(290, 270, 296, 32);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("COMPANY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 260, 32);
        getContentPane().add(f);
        f.setBounds(290, 310, 296, 32);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("DETAILS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 310, 260, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCT NAME", "PRODUCT PRICE", "QUANTITY OR WEIGHT", "COMPANY", "DETAILS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 110, 740, 360);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(710, 490, 210, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Product/p1s.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 490, 440, 30);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(940, 490, 100, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Product/exit.JPG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1230, 0, 140, 30);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Product/back.JPG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 110, 33);

        jButton7.setText("exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1330, 0, 40, 30);

        jButton8.setText("back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(80, 0, 30, 30);

        jButton9.setText("back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 0, 20, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 430, 100, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("DELATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 430, 90, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(380, 430, 90, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 430, 80, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 430, 90, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "PES", "KG", "MG", "G", "L", "ML" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(430, 230, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // EXIT 
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 void Clear(){
         b.setText("");
         c.setText("");
         d.setText("");
         e.setText("");
         f.setText("");
        
         b.requestFocus();
         String dd="SELECT * FROM `product`";
        Showtable(dd);
        a.setText(""+Autoid());
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // CLEAR
       Clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        b.requestFocus();
        }
    }//GEN-LAST:event_aKeyPressed

    private void bKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        c.requestFocus();
        }
    }//GEN-LAST:event_bKeyPressed

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       d.requestFocus();
        }
    }//GEN-LAST:event_cKeyPressed

    private void dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyPressed
        // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        e.requestFocus();
        }
    }//GEN-LAST:event_dKeyPressed
       //Auto ID 
    int Autoid(){int at=0;
        String sq="SELECT `ID` FROM `product`";
        Con();
    try {
        rs=st.executeQuery(sq);
        while(rs.next()){
        at=rs.getInt(1);
        }
        at++;
        
        } catch (SQLException ex) {
            Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
        }
      return at;
    }
//data  show table
    void Showtable(String dd){
        DefaultTableModel ddt=(DefaultTableModel)jTable1.getModel();
            ddt.setRowCount(0);
            Con();
            
        try {
          rs=st.executeQuery(dd);
            while(rs.next()){
            ddt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void eKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKeyPressed
       // Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        f.requestFocus();
        }
    }//GEN-LAST:event_eKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Insert Data
        String id=a.getText();
        String name=b.getText();
        String price=c.getText();
        String quantity=d.getText();
        String company=e.getText();
        String details=f.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, " ID is Empty!!");
            a.requestFocus();
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, " Name is Empty!!");
            b.requestFocus();
        }
        else if(price.isEmpty()){
            JOptionPane.showMessageDialog(this, " Price is Empty!!");
            c.requestFocus();
        }
        else if(quantity.isEmpty()){
            JOptionPane.showMessageDialog(this, " Quantity is Empty!!");
            d.requestFocus();
        }
        else if(company.isEmpty()){
            JOptionPane.showMessageDialog(this, " Company is Empty!!");
            e.requestFocus();
        }
        else if(details.isEmpty()){
            JOptionPane.showMessageDialog(this, " Details is Empty!!");
            f.requestFocus();
        }
        else{
            try {
String sq="INSERT INTO `product` (`ID`,`Product Name`,`Price`,`Quantity or Weight`,`Company`,`Details`) VALUES ('"+id+"','"+name+"','"+price+"','"+quantity+"','"+company+"','"+details+"')";
                Con();
               int i=st.executeUpdate(sq);
                if(i>=1){
                JOptionPane.showMessageDialog(this, "Data Insert Success");
                Clear();
                String dd="SELECT * FROM `product`";
                Showtable(dd);
                a.setText(""+Autoid());
                }
                else{
                JOptionPane.showMessageDialog(this, "Data Insert Failed!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Mouse Click
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        a.setText(dt.getValueAt(jTable1.getSelectedRow(), 0).toString());
        b.setText(dt.getValueAt(jTable1.getSelectedRow(), 1).toString());
        c.setText(dt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        d.setText(dt.getValueAt(jTable1.getSelectedRow(), 3).toString());
        e.setText(dt.getValueAt(jTable1.getSelectedRow(), 4).toString());
        f.setText(dt.getValueAt(jTable1.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked
void Delete(){
            String name=b.getText();
            String price=c.getText();
            String quantity=d.getText();
            String company=e.getText();
            String details=f.getText();
            try {
            String sq="DELETE FROM `product` WHERE `Product Name`='"+name+"' and `Price`='"+price+"'";
            Con();
            int u=st.executeUpdate(sq);
            if(u>=1){
                JOptionPane.showMessageDialog(this, "Delete Successfull");
            Clear();
            String dd="SELECT * FROM `product`";
        Showtable(dd);
           
            }
            else{
           JOptionPane.showMessageDialog(this, "Delete Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // Delete
            
        Delete();
    }//GEN-LAST:event_jButton4ActionPerformed

    void Update(){
       
        String id=a.getText();
        String name=b.getText();
        String price=c.getText();
        String quantity=d.getText();
        String company=e.getText();
        String details=f.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, " ID is Empty!!");
            a.requestFocus();
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, " Name is Empty!!");
            b.requestFocus();
        }
        else if(price.isEmpty()){
            JOptionPane.showMessageDialog(this, " Price is Empty!!");
            c.requestFocus();
        }
        else if(quantity.isEmpty()){
            JOptionPane.showMessageDialog(this, " Quantity is Empty!!");
            d.requestFocus();
        }
        else if(company.isEmpty()){
            JOptionPane.showMessageDialog(this, " Company is Empty!!");
            e.requestFocus();
        }
        else if(details.isEmpty()){
            JOptionPane.showMessageDialog(this, " Details is Empty!!");
            f.requestFocus();
        }
        else{
            try {
 String up="UPDATE `product` SET `Product Name`='"+name+"',`Price`='"+price+"',`Quantity or Weight`='"+quantity+"',`Company`='"+company+"',`Details`='"+details+"' WHERE `ID`='"+id+"'";
                Con();
               int u=st.executeUpdate(up);
                if(u>=1){
                JOptionPane.showMessageDialog(this, "Data Update Success");
                Clear();
                String dd="SELECT * FROM `product`";
                Showtable(dd);
                a.setText(""+Autoid());
                }
                else{
                JOptionPane.showMessageDialog(this, "Data Update Failed!!");
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(product_table.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            // Upgrade
            Update();
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Find Data
        String sq="SELECT *FROM `product` WHERE `ID`='"+jTextField1.getText()+"' OR `Product Name`='"+jTextField1.getText()+"' "
                + "OR `Company`='"+jTextField1.getText()+"' OR `Details`='"+jTextField1.getText()+"'";
        Showtable(sq);
        jTextField1.setText("");
        jTextField1.requestFocus();       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        //Find Enter 
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String sq="SELECT *FROM `product` WHERE `ID`='"+jTextField1.getText()+"' OR `Product Name`='"+jTextField1.getText()+"' "
                + "OR `Company`='"+jTextField1.getText()+"' OR `Details`='"+jTextField1.getText()+"'";
        Showtable(sq);
        jTextField1.requestFocus();
        jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Exit 2
        this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // back
        table_page tp=new table_page();
        this.setVisible(false);
        tp.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // back
        table_page tp=new table_page();
        this.setVisible(false);
        tp.setVisible(true); 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //
        
        d.setText(d.getText()+"  "+jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
